### ISSUE TITLE
Rewrite in TypeScript

### ISSUE THREAD

**Issue by 2Shaun** [2Shaun/guesstimoji#30]
**Is your feature request related to a problem? Please describe.**
TypeScript is easier to debug and manage 

**Additional context**
I love types

**Comment by AbhinavMadahar** [comment]
According to [this guide](https://github.com/typescript-cheatsheets/react#section-2-getting-started), this is the idiomatic way to type props. If you personally like this style, we can do this with the other components. I'll also write new components in this style.
